[package]
name = "tabbed-document-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
im.workspace = true
floem = { path = "../..", features = ["rfd-tokio"] }

slotmap = { version = "1.0.7" }

serde = { version = "1.0.210", features = ["derive"] }
serde_json = { version = "1.0.128" }